# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Java Properties
java_version = 25

# Fabric Properties
# check these on https://fabricmc.net/develop
loom_version = 1.18.2
minecraft_version = 26.3
loader_version = 0.19.5

# Dependencies
fabric_api_version = 0.161.0+26.3
geckolib_version = 5.5.6
lambdynlights_version = 4.13.0

# Mod Properties
mod_version = 1.0.2
maven_group = mielon.thesift
archives_base_name = mielons-the-sift
mod_name = Mielon's The Sift
mod_id = the_sift
mod_author = Mielon
mod_description = Explore The Sift: a strange dimension of siftslate, Ichor, ancient life, and resonant souls.
