package mielon.thesift.block;

import java.util.Optional;
import java.util.Set;
import java.util.function.Function;
import mielon.thesift.block.entity.SiftPortalBlockEntity;
import mielon.thesift.block.entity.SonorousDeepslateBlockEntity;
import net.fabricmc.fabric.api.item.v1.BlockTransformerHelper;
import net.fabricmc.fabric.api.item.v1.DefaultItemComponentEvents;
import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;
import net.minecraft.core.Direction;
import net.minecraft.core.Registry;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.HangingSignItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.StandingAndWallBlockItem;
import net.minecraft.world.item.component.Compostable;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.CeilingHangingSignBlock;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.FenceGateBlock;
import net.minecraft.world.level.block.HangingRootsBlock;
import net.minecraft.world.level.block.LayeredCauldronBlock;
import net.minecraft.world.level.block.PressurePlateBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.ShelfBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SnowLayerBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.StandingSignBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.WallHangingSignBlock;
import net.minecraft.world.level.block.WallSignBlock;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.entity.BlockEntityTypes;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.providers.number.ints.ResolvableInt;

public class ModBlocks {
   public static final ResourceKey SIFT_PORTAL_KEY;
   public static final Block SIFT_PORTAL;
   public static final ResourceKey SIFT_PORTAL_ITEM_KEY;
   public static final BlockItem SIFT_PORTAL_ITEM;
   public static final ResourceKey SIFT_PORTAL_BLOCK_ENTITY_KEY;
   public static final BlockEntityType SIFT_PORTAL_BLOCK_ENTITY;
   public static final ResourceKey SONOROUS_DEEPSLATE_KEY;
   public static final Block SONOROUS_DEEPSLATE;
   public static final ResourceKey SONOROUS_DEEPSLATE_ITEM_KEY;
   public static final BlockItem SONOROUS_DEEPSLATE_ITEM;
   public static final ResourceKey SONOROUS_DEEPSLATE_BLOCK_ENTITY_KEY;
   public static final BlockEntityType SONOROUS_DEEPSLATE_BLOCK_ENTITY;
   public static final ResourceKey SIFTSLATE_KEY;
   public static final Block SIFTSLATE;
   public static final ResourceKey SIFTSLATE_ITEM_KEY;
   public static final BlockItem SIFTSLATE_ITEM;
   public static final ResourceKey SIFTSLATE_GROWTH_KEY;
   public static final Block SIFTSLATE_GROWTH;
   public static final ResourceKey SIFTSLATE_GROWTH_ITEM_KEY;
   public static final BlockItem SIFTSLATE_GROWTH_ITEM;
   public static final Block ICHOR_SNOW_BLOCK;
   public static final BlockItem ICHOR_SNOW_BLOCK_ITEM;
   public static final SnowLayerBlock ICHOR_SNOW;
   public static final BlockItem ICHOR_SNOW_ITEM;
   public static final SculkflowerCropBlock SCULKFLOWER_CROP;
   public static final SculkflowerBlock SCULKFLOWER;
   public static final BlockItem SCULKFLOWER_ITEM;
   public static final ResourceKey HEALTHY_SCULK_KEY;
   public static final Block HEALTHY_SCULK;
   public static final ResourceKey HEALTHY_SCULK_ITEM_KEY;
   public static final BlockItem HEALTHY_SCULK_ITEM;
   public static final ResourceKey DRY_HEALTHY_SCULK_KEY;
   public static final Block DRY_HEALTHY_SCULK;
   public static final ResourceKey DRY_HEALTHY_SCULK_ITEM_KEY;
   public static final BlockItem DRY_HEALTHY_SCULK_ITEM;
   public static final ResourceKey DRY_HEALTHY_SCULK_GROWTH_KEY;
   public static final Block DRY_HEALTHY_SCULK_GROWTH;
   public static final ResourceKey DRY_HEALTHY_SCULK_GROWTH_ITEM_KEY;
   public static final BlockItem DRY_HEALTHY_SCULK_GROWTH_ITEM;
   public static final ResourceKey ICHOR_CAULDRON_KEY;
   public static final Block ICHOR_CAULDRON;
   public static final ResourceKey SOUL_BLOCK_KEY;
   public static final Block SOUL_BLOCK;
   public static final ResourceKey SOUL_BLOCK_ITEM_KEY;
   public static final BlockItem SOUL_BLOCK_ITEM;
   public static final ResourceKey OVERGROWN_CHARD_KEY;
   public static final Block OVERGROWN_CHARD;
   public static final ResourceKey OVERGROWN_CHARD_ITEM_KEY;
   public static final BlockItem OVERGROWN_CHARD_ITEM;
   public static final ResourceKey OVERGROWN_STALKS_KEY;
   public static final Block OVERGROWN_STALKS;
   public static final ResourceKey OVERGROWN_STALKS_ITEM_KEY;
   public static final BlockItem OVERGROWN_STALKS_ITEM;
   public static final ResourceKey OVERGROWN_FRONDS_KEY;
   public static final Block OVERGROWN_FRONDS;
   public static final ResourceKey OVERGROWN_FRONDS_ITEM_KEY;
   public static final BlockItem OVERGROWN_FRONDS_ITEM;
   public static final ResourceKey OVERGROWN_LOTUS_KEY;
   public static final Block OVERGROWN_LOTUS;
   public static final ResourceKey OVERGROWN_LOTUS_ITEM_KEY;
   public static final BlockItem OVERGROWN_LOTUS_ITEM;
   public static final ResourceKey SUNBURST_PLANT_KEY;
   public static final Block SUNBURST_PLANT;
   public static final ResourceKey SUNBURST_PLANT_ITEM_KEY;
   public static final BlockItem SUNBURST_PLANT_ITEM;
   public static final ResourceKey WHISPERBLOOM_KEY;
   public static final Block WHISPERBLOOM;
   public static final ResourceKey WHISPERBLOOM_ITEM_KEY;
   public static final BlockItem WHISPERBLOOM_ITEM;
   public static final ResourceKey SIFTSLATE_STALKS_KEY;
   public static final Block SIFTSLATE_STALKS;
   public static final ResourceKey SIFTSLATE_STALKS_ITEM_KEY;
   public static final BlockItem SIFTSLATE_STALKS_ITEM;
   public static final ResourceKey HEALTHY_SCULK_SPROUTS_KEY;
   public static final Block HEALTHY_SCULK_SPROUTS;
   public static final ResourceKey HEALTHY_SCULK_SPROUTS_ITEM_KEY;
   public static final BlockItem HEALTHY_SCULK_SPROUTS_ITEM;
   public static final ResourceKey DRY_HEALTHY_SCULK_SPROUTS_KEY;
   public static final Block DRY_HEALTHY_SCULK_SPROUTS;
   public static final ResourceKey DRY_HEALTHY_SCULK_SPROUTS_ITEM_KEY;
   public static final BlockItem DRY_HEALTHY_SCULK_SPROUTS_ITEM;
   public static final Block SIFTSLATE_HANGING_ROOTS;
   public static final BlockItem SIFTSLATE_HANGING_ROOTS_ITEM;
   public static final Block OVERGROWN_HANGING_ROOTS;
   public static final BlockItem OVERGROWN_HANGING_ROOTS_ITEM;
   public static final Block OVERGROWN_WILLOW_PLANKS;
   public static final BlockItem OVERGROWN_WILLOW_PLANKS_ITEM;
   public static final Block OVERGROWN_WILLOW_LOG;
   public static final BlockItem OVERGROWN_WILLOW_LOG_ITEM;
   public static final Block OVERGROWN_WILLOW_WOOD;
   public static final BlockItem OVERGROWN_WILLOW_WOOD_ITEM;
   public static final Block STRIPPED_OVERGROWN_WILLOW_LOG;
   public static final BlockItem STRIPPED_OVERGROWN_WILLOW_LOG_ITEM;
   public static final Block STRIPPED_OVERGROWN_WILLOW_WOOD;
   public static final BlockItem STRIPPED_OVERGROWN_WILLOW_WOOD_ITEM;
   public static final Block OVERGROWN_WILLOW_STAIRS;
   public static final BlockItem OVERGROWN_WILLOW_STAIRS_ITEM;
   public static final Block OVERGROWN_WILLOW_SLAB;
   public static final BlockItem OVERGROWN_WILLOW_SLAB_ITEM;
   public static final Block OVERGROWN_WILLOW_FENCE;
   public static final BlockItem OVERGROWN_WILLOW_FENCE_ITEM;
   public static final Block OVERGROWN_WILLOW_FENCE_GATE;
   public static final BlockItem OVERGROWN_WILLOW_FENCE_GATE_ITEM;
   public static final Block OVERGROWN_WILLOW_DOOR;
   public static final BlockItem OVERGROWN_WILLOW_DOOR_ITEM;
   public static final Block OVERGROWN_WILLOW_TRAPDOOR;
   public static final BlockItem OVERGROWN_WILLOW_TRAPDOOR_ITEM;
   public static final Block OVERGROWN_WILLOW_PRESSURE_PLATE;
   public static final BlockItem OVERGROWN_WILLOW_PRESSURE_PLATE_ITEM;
   public static final Block OVERGROWN_WILLOW_BUTTON;
   public static final BlockItem OVERGROWN_WILLOW_BUTTON_ITEM;
   public static final Block OVERGROWN_WILLOW_SHELF;
   public static final BlockItem OVERGROWN_WILLOW_SHELF_ITEM;
   public static final Block OVERGROWN_WILLOW_SIGN;
   public static final Block OVERGROWN_WILLOW_WALL_SIGN;
   public static final Item OVERGROWN_WILLOW_SIGN_ITEM;
   public static final Block OVERGROWN_WILLOW_HANGING_SIGN;
   public static final Block OVERGROWN_WILLOW_WALL_HANGING_SIGN;
   public static final Item OVERGROWN_WILLOW_HANGING_SIGN_ITEM;
   public static final Block OVERGROWN_WILLOW_FOLIAGE;
   public static final BlockItem OVERGROWN_WILLOW_FOLIAGE_ITEM;
   public static final Block OVERGROWN_WILLOW_SAPLING;
   public static final BlockItem OVERGROWN_WILLOW_SAPLING_ITEM;
   public static final Block OVERGROWN_WILLOW_VINES;
   public static final BlockItem OVERGROWN_WILLOW_VINES_ITEM;
   public static final Block OVERGROWN_WILLOW_VINES_PLANT;
   public static final DropExperienceBlock SIFTSLATE_COAL_ORE;
   public static final BlockItem SIFTSLATE_COAL_ORE_ITEM;
   public static final DropExperienceBlock SIFTSLATE_DIAMOND_ORE;
   public static final BlockItem SIFTSLATE_DIAMOND_ORE_ITEM;
   public static final DropExperienceBlock SIFTSLATE_EMERALD_ORE;
   public static final BlockItem SIFTSLATE_EMERALD_ORE_ITEM;
   public static final DropExperienceBlock SIFTSLATE_CHAROITE_ORE;
   public static final BlockItem SIFTSLATE_CHAROITE_ORE_ITEM;
   public static final DropExperienceBlock SIFTSLATE_SIFTITE_ORE;
   public static final BlockItem SIFTSLATE_SIFTITE_ORE_ITEM;
   public static final ResourceKey REINFORCED_SIFTSLATE_KEY;
   public static final Block REINFORCED_SIFTSLATE;
   public static final ResourceKey REINFORCED_SIFTSLATE_ITEM_KEY;
   public static final BlockItem REINFORCED_SIFTSLATE_ITEM;

   private static ResourceKey blockKey(String name) {
      return ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", name));
   }

   private static ResourceKey itemKey(String name) {
      return ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", name));
   }

   private static <T extends Block> T registerBlock(String name, Function<BlockBehaviour.Properties, T> factory, BlockBehaviour.Properties properties) {
      ResourceKey<Block> key = blockKey(name);
      return (T)Registry.register(BuiltInRegistries.BLOCK, key, factory.apply(properties.setId(key)));
   }

   private static BlockItem registerBlockItem(String name, Block block) {
      ResourceKey<Item> key = itemKey(name);
      return (BlockItem)Registry.register(BuiltInRegistries.ITEM, key, new BlockItem(block, (new Item.Properties()).setId(key)));
   }

   private static <T extends Item> T registerItem(String name, Function<Item.Properties, T> factory) {
      ResourceKey<Item> key = itemKey(name);
      return (T)Registry.register(BuiltInRegistries.ITEM, key, factory.apply((new Item.Properties()).setId(key)));
   }

   private static BlockBehaviour.Properties dropsLike(BlockBehaviour.Properties properties, String lootTableName) {
      ResourceKey<LootTable> lootTable = ResourceKey.create(Registries.LOOT_TABLE, Identifier.fromNamespaceAndPath("the_sift", "blocks/" + lootTableName));
      return properties.overrideLootTable(Optional.of(lootTable));
   }

   private static Compostable compostable(int chancePercent) {
      return new Compostable(new ResolvableInt.Constant(chancePercent));
   }

   public static void initialize() {
      IchorCauldronInteractions.register();
      DefaultItemComponentEvents.MODIFY.register((DefaultItemComponentEvents.ModifyCallback)(context) -> {
         context.modify(OVERGROWN_CHARD_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_STALKS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_FRONDS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_LOTUS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(65)));
         context.modify(SUNBURST_PLANT_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(65)));
         context.modify(WHISPERBLOOM_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(65)));
         context.modify(SIFTSLATE_STALKS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(HEALTHY_SCULK_SPROUTS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(DRY_HEALTHY_SCULK_SPROUTS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(SIFTSLATE_HANGING_ROOTS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_HANGING_ROOTS_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_WILLOW_FOLIAGE_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_WILLOW_SAPLING_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(30)));
         context.modify(OVERGROWN_WILLOW_VINES_ITEM, (builder) -> builder.set(DataComponents.COMPOSTABLE, compostable(50)));
      });
      BlockTransformerHelper.registerStripping(OVERGROWN_WILLOW_LOG, STRIPPED_OVERGROWN_WILLOW_LOG);
      BlockTransformerHelper.registerStripping(OVERGROWN_WILLOW_WOOD, STRIPPED_OVERGROWN_WILLOW_WOOD);
      FlammableBlockRegistry flammable = FlammableBlockRegistry.getDefaultInstance();
      flammable.add(OVERGROWN_WILLOW_LOG, 5, 5);
      flammable.add(OVERGROWN_WILLOW_WOOD, 5, 5);
      flammable.add(STRIPPED_OVERGROWN_WILLOW_LOG, 5, 5);
      flammable.add(STRIPPED_OVERGROWN_WILLOW_WOOD, 5, 5);
      flammable.add(OVERGROWN_WILLOW_PLANKS, 5, 20);
      flammable.add(OVERGROWN_WILLOW_STAIRS, 5, 20);
      flammable.add(OVERGROWN_WILLOW_SLAB, 5, 20);
      flammable.add(OVERGROWN_WILLOW_FENCE, 5, 20);
      flammable.add(OVERGROWN_WILLOW_FENCE_GATE, 5, 20);
      flammable.add(OVERGROWN_WILLOW_DOOR, 5, 20);
      flammable.add(OVERGROWN_WILLOW_TRAPDOOR, 5, 20);
      flammable.add(OVERGROWN_WILLOW_PRESSURE_PLATE, 5, 20);
      flammable.add(OVERGROWN_WILLOW_BUTTON, 5, 20);
      flammable.add(OVERGROWN_WILLOW_SHELF, 5, 20);
      flammable.add(OVERGROWN_WILLOW_SIGN, 5, 20);
      flammable.add(OVERGROWN_WILLOW_WALL_SIGN, 5, 20);
      flammable.add(OVERGROWN_WILLOW_HANGING_SIGN, 5, 20);
      flammable.add(OVERGROWN_WILLOW_WALL_HANGING_SIGN, 5, 20);
      flammable.add(OVERGROWN_WILLOW_FOLIAGE, 30, 60);
      flammable.add(OVERGROWN_WILLOW_SAPLING, 60, 100);
      BlockEntityTypes.SIGN.addValidBlock(OVERGROWN_WILLOW_SIGN);
      BlockEntityTypes.SIGN.addValidBlock(OVERGROWN_WILLOW_WALL_SIGN);
      BlockEntityTypes.HANGING_SIGN.addValidBlock(OVERGROWN_WILLOW_HANGING_SIGN);
      BlockEntityTypes.HANGING_SIGN.addValidBlock(OVERGROWN_WILLOW_WALL_HANGING_SIGN);
      BlockEntityTypes.SHELF.addValidBlock(OVERGROWN_WILLOW_SHELF);
   }

   static {
      SIFT_PORTAL_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "sift_portal"));
      SIFT_PORTAL = (Block)Registry.register(BuiltInRegistries.BLOCK, SIFT_PORTAL_KEY, new SiftPortalBlock(Properties.ofFullCopy(Blocks.NETHER_PORTAL).setId(SIFT_PORTAL_KEY).noCollision().noOcclusion().strength(-1.0F).lightLevel((state) -> 12)));
      SIFT_PORTAL_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "sift_portal"));
      SIFT_PORTAL_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SIFT_PORTAL_ITEM_KEY, new BlockItem(SIFT_PORTAL, (new Item.Properties()).setId(SIFT_PORTAL_ITEM_KEY)));
      SIFT_PORTAL_BLOCK_ENTITY_KEY = ResourceKey.create(BuiltInRegistries.BLOCK_ENTITY_TYPE.key(), Identifier.fromNamespaceAndPath("the_sift", "sift_portal"));
      SIFT_PORTAL_BLOCK_ENTITY = (BlockEntityType)Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, SIFT_PORTAL_BLOCK_ENTITY_KEY, new BlockEntityType(SiftPortalBlockEntity::new, Set.of(SIFT_PORTAL)));
      SONOROUS_DEEPSLATE_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "sonorous_deepslate"));
      SONOROUS_DEEPSLATE = (Block)Registry.register(BuiltInRegistries.BLOCK, SONOROUS_DEEPSLATE_KEY, new SonorousDeepslateBlock(Properties.ofFullCopy(Blocks.REINFORCED_DEEPSLATE).setId(SONOROUS_DEEPSLATE_KEY)));
      SONOROUS_DEEPSLATE_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "sonorous_deepslate"));
      SONOROUS_DEEPSLATE_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SONOROUS_DEEPSLATE_ITEM_KEY, new SonorousDeepslateBlockItem(SONOROUS_DEEPSLATE, (new Item.Properties()).setId(SONOROUS_DEEPSLATE_ITEM_KEY)));
      SONOROUS_DEEPSLATE_BLOCK_ENTITY_KEY = ResourceKey.create(BuiltInRegistries.BLOCK_ENTITY_TYPE.key(), Identifier.fromNamespaceAndPath("the_sift", "sonorous_deepslate"));
      SONOROUS_DEEPSLATE_BLOCK_ENTITY = (BlockEntityType)Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, SONOROUS_DEEPSLATE_BLOCK_ENTITY_KEY, new BlockEntityType(SonorousDeepslateBlockEntity::new, Set.of(SONOROUS_DEEPSLATE)));
      SIFTSLATE_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "siftslate"));
      SIFTSLATE = (Block)Registry.register(BuiltInRegistries.BLOCK, SIFTSLATE_KEY, new Block(Properties.ofFullCopy(Blocks.DEEPSLATE).setId(SIFTSLATE_KEY)));
      SIFTSLATE_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "siftslate"));
      SIFTSLATE_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SIFTSLATE_ITEM_KEY, new BlockItem(SIFTSLATE, (new Item.Properties()).setId(SIFTSLATE_ITEM_KEY)));
      SIFTSLATE_GROWTH_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "siftslate_growth"));
      SIFTSLATE_GROWTH = (Block)Registry.register(BuiltInRegistries.BLOCK, SIFTSLATE_GROWTH_KEY, new SiftslateGrowthBlock(Properties.ofFullCopy(Blocks.STONE).sound(SoundType.DEEPSLATE).randomTicks().setId(SIFTSLATE_GROWTH_KEY)));
      SIFTSLATE_GROWTH_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "siftslate_growth"));
      SIFTSLATE_GROWTH_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SIFTSLATE_GROWTH_ITEM_KEY, new BlockItem(SIFTSLATE_GROWTH, (new Item.Properties()).setId(SIFTSLATE_GROWTH_ITEM_KEY)));
      ICHOR_SNOW_BLOCK = registerBlock("ichor_snow_block", Block::new, Properties.ofFullCopy(Blocks.SNOW_BLOCK));
      ICHOR_SNOW_BLOCK_ITEM = registerBlockItem("ichor_snow_block", ICHOR_SNOW_BLOCK);
      ICHOR_SNOW = (SnowLayerBlock)registerBlock("ichor_snow", SnowLayerBlock::new, Properties.ofFullCopy(Blocks.SNOW));
      ICHOR_SNOW_ITEM = registerBlockItem("ichor_snow", ICHOR_SNOW);
      SCULKFLOWER_CROP = (SculkflowerCropBlock)registerBlock("sculkflower_crop", SculkflowerCropBlock::new, Properties.ofFullCopy(Blocks.TORCHFLOWER_CROP).randomTicks());
      SCULKFLOWER = (SculkflowerBlock)registerBlock("sculkflower", SculkflowerBlock::new, Properties.ofFullCopy(Blocks.CACTUS_FLOWER));
      SCULKFLOWER_ITEM = registerBlockItem("sculkflower", SCULKFLOWER);
      HEALTHY_SCULK_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "healthy_sculk"));
      HEALTHY_SCULK = (Block)Registry.register(BuiltInRegistries.BLOCK, HEALTHY_SCULK_KEY, new Block(Properties.ofFullCopy(Blocks.SCULK).setId(HEALTHY_SCULK_KEY)));
      HEALTHY_SCULK_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "healthy_sculk"));
      HEALTHY_SCULK_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, HEALTHY_SCULK_ITEM_KEY, new BlockItem(HEALTHY_SCULK, (new Item.Properties()).setId(HEALTHY_SCULK_ITEM_KEY)));
      DRY_HEALTHY_SCULK_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "dry_healthy_sculk"));
      DRY_HEALTHY_SCULK = (Block)Registry.register(BuiltInRegistries.BLOCK, DRY_HEALTHY_SCULK_KEY, new Block(Properties.ofFullCopy(Blocks.SCULK).setId(DRY_HEALTHY_SCULK_KEY)));
      DRY_HEALTHY_SCULK_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "dry_healthy_sculk"));
      DRY_HEALTHY_SCULK_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, DRY_HEALTHY_SCULK_ITEM_KEY, new BlockItem(DRY_HEALTHY_SCULK, (new Item.Properties()).setId(DRY_HEALTHY_SCULK_ITEM_KEY)));
      DRY_HEALTHY_SCULK_GROWTH_KEY = blockKey("dry_healthy_sculk_growth");
      DRY_HEALTHY_SCULK_GROWTH = (Block)Registry.register(BuiltInRegistries.BLOCK, DRY_HEALTHY_SCULK_GROWTH_KEY, new DryHealthySculkGrowthBlock(Properties.ofFullCopy(Blocks.SCULK).randomTicks().setId(DRY_HEALTHY_SCULK_GROWTH_KEY)));
      DRY_HEALTHY_SCULK_GROWTH_ITEM_KEY = itemKey("dry_healthy_sculk_growth");
      DRY_HEALTHY_SCULK_GROWTH_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, DRY_HEALTHY_SCULK_GROWTH_ITEM_KEY, new BlockItem(DRY_HEALTHY_SCULK_GROWTH, (new Item.Properties()).setId(DRY_HEALTHY_SCULK_GROWTH_ITEM_KEY)));
      ICHOR_CAULDRON_KEY = blockKey("ichor_cauldron");
      ICHOR_CAULDRON = (Block)Registry.register(BuiltInRegistries.BLOCK, ICHOR_CAULDRON_KEY, new IchorCauldronBlock(Properties.ofFullCopy(Blocks.WATER_CAULDRON).setId(ICHOR_CAULDRON_KEY).lightLevel((state) -> (Integer)state.getValue(LayeredCauldronBlock.LEVEL) * 5)));
      SOUL_BLOCK_KEY = blockKey("soul_block");
      SOUL_BLOCK = (Block)Registry.register(BuiltInRegistries.BLOCK, SOUL_BLOCK_KEY, new SoulBlock(Properties.ofFullCopy(Blocks.SOUL_SOIL).strength(0.35F, 0.35F).sound(SoundType.SOUL_SOIL).lightLevel((state) -> 14).noLootTable().setId(SOUL_BLOCK_KEY)));
      SOUL_BLOCK_ITEM_KEY = itemKey("soul_block");
      SOUL_BLOCK_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SOUL_BLOCK_ITEM_KEY, new BlockItem(SOUL_BLOCK, (new Item.Properties()).setId(SOUL_BLOCK_ITEM_KEY)));
      OVERGROWN_CHARD_KEY = blockKey("overgrown_chard");
      OVERGROWN_CHARD = (Block)Registry.register(BuiltInRegistries.BLOCK, OVERGROWN_CHARD_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.BEETROOTS).replaceable().setId(OVERGROWN_CHARD_KEY)));
      OVERGROWN_CHARD_ITEM_KEY = itemKey("overgrown_chard");
      OVERGROWN_CHARD_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, OVERGROWN_CHARD_ITEM_KEY, new BlockItem(OVERGROWN_CHARD, (new Item.Properties()).setId(OVERGROWN_CHARD_ITEM_KEY)));
      OVERGROWN_STALKS_KEY = blockKey("overgrown_stalks");
      OVERGROWN_STALKS = (Block)Registry.register(BuiltInRegistries.BLOCK, OVERGROWN_STALKS_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(OVERGROWN_STALKS_KEY)));
      OVERGROWN_STALKS_ITEM_KEY = itemKey("overgrown_stalks");
      OVERGROWN_STALKS_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, OVERGROWN_STALKS_ITEM_KEY, new BlockItem(OVERGROWN_STALKS, (new Item.Properties()).setId(OVERGROWN_STALKS_ITEM_KEY)));
      OVERGROWN_FRONDS_KEY = blockKey("overgrown_fronds");
      OVERGROWN_FRONDS = (Block)Registry.register(BuiltInRegistries.BLOCK, OVERGROWN_FRONDS_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(OVERGROWN_FRONDS_KEY)));
      OVERGROWN_FRONDS_ITEM_KEY = itemKey("overgrown_fronds");
      OVERGROWN_FRONDS_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, OVERGROWN_FRONDS_ITEM_KEY, new BlockItem(OVERGROWN_FRONDS, (new Item.Properties()).setId(OVERGROWN_FRONDS_ITEM_KEY)));
      OVERGROWN_LOTUS_KEY = blockKey("overgrown_lotus");
      OVERGROWN_LOTUS = (Block)Registry.register(BuiltInRegistries.BLOCK, OVERGROWN_LOTUS_KEY, new OvergrownLotusBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(OVERGROWN_LOTUS_KEY)));
      OVERGROWN_LOTUS_ITEM_KEY = itemKey("overgrown_lotus");
      OVERGROWN_LOTUS_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, OVERGROWN_LOTUS_ITEM_KEY, new BlockItem(OVERGROWN_LOTUS, (new Item.Properties()).setId(OVERGROWN_LOTUS_ITEM_KEY)));
      SUNBURST_PLANT_KEY = blockKey("sunburst_plant");
      SUNBURST_PLANT = (Block)Registry.register(BuiltInRegistries.BLOCK, SUNBURST_PLANT_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(SUNBURST_PLANT_KEY), true));
      SUNBURST_PLANT_ITEM_KEY = itemKey("sunburst_plant");
      SUNBURST_PLANT_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SUNBURST_PLANT_ITEM_KEY, new BlockItem(SUNBURST_PLANT, (new Item.Properties()).setId(SUNBURST_PLANT_ITEM_KEY)));
      WHISPERBLOOM_KEY = blockKey("whisperbloom");
      WHISPERBLOOM = (Block)Registry.register(BuiltInRegistries.BLOCK, WHISPERBLOOM_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(WHISPERBLOOM_KEY), true));
      WHISPERBLOOM_ITEM_KEY = itemKey("whisperbloom");
      WHISPERBLOOM_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, WHISPERBLOOM_ITEM_KEY, new BlockItem(WHISPERBLOOM, (new Item.Properties()).setId(WHISPERBLOOM_ITEM_KEY)));
      SIFTSLATE_STALKS_KEY = blockKey("siftslate_stalks");
      SIFTSLATE_STALKS = (Block)Registry.register(BuiltInRegistries.BLOCK, SIFTSLATE_STALKS_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(SIFTSLATE_STALKS_KEY)));
      SIFTSLATE_STALKS_ITEM_KEY = itemKey("siftslate_stalks");
      SIFTSLATE_STALKS_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, SIFTSLATE_STALKS_ITEM_KEY, new BlockItem(SIFTSLATE_STALKS, (new Item.Properties()).setId(SIFTSLATE_STALKS_ITEM_KEY)));
      HEALTHY_SCULK_SPROUTS_KEY = blockKey("healthy_sculk_sprouts");
      HEALTHY_SCULK_SPROUTS = (Block)Registry.register(BuiltInRegistries.BLOCK, HEALTHY_SCULK_SPROUTS_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(HEALTHY_SCULK_SPROUTS_KEY)));
      HEALTHY_SCULK_SPROUTS_ITEM_KEY = itemKey("healthy_sculk_sprouts");
      HEALTHY_SCULK_SPROUTS_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, HEALTHY_SCULK_SPROUTS_ITEM_KEY, new BlockItem(HEALTHY_SCULK_SPROUTS, (new Item.Properties()).setId(HEALTHY_SCULK_SPROUTS_ITEM_KEY)));
      DRY_HEALTHY_SCULK_SPROUTS_KEY = blockKey("dry_healthy_sculk_sprouts");
      DRY_HEALTHY_SCULK_SPROUTS = (Block)Registry.register(BuiltInRegistries.BLOCK, DRY_HEALTHY_SCULK_SPROUTS_KEY, new SiftPlantBlock(Properties.ofFullCopy(Blocks.NETHER_SPROUTS).setId(DRY_HEALTHY_SCULK_SPROUTS_KEY)));
      DRY_HEALTHY_SCULK_SPROUTS_ITEM_KEY = itemKey("dry_healthy_sculk_sprouts");
      DRY_HEALTHY_SCULK_SPROUTS_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, DRY_HEALTHY_SCULK_SPROUTS_ITEM_KEY, new BlockItem(DRY_HEALTHY_SCULK_SPROUTS, (new Item.Properties()).setId(DRY_HEALTHY_SCULK_SPROUTS_ITEM_KEY)));
      SIFTSLATE_HANGING_ROOTS = registerBlock("siftslate_hanging_roots", HangingRootsBlock::new, Properties.ofFullCopy(Blocks.HANGING_ROOTS).sound(SoundType.NETHER_SPROUTS));
      SIFTSLATE_HANGING_ROOTS_ITEM = registerBlockItem("siftslate_hanging_roots", SIFTSLATE_HANGING_ROOTS);
      OVERGROWN_HANGING_ROOTS = registerBlock("overgrown_hanging_roots", HangingRootsBlock::new, Properties.ofFullCopy(Blocks.HANGING_ROOTS).sound(SoundType.NETHER_SPROUTS));
      OVERGROWN_HANGING_ROOTS_ITEM = registerBlockItem("overgrown_hanging_roots", OVERGROWN_HANGING_ROOTS);
      OVERGROWN_WILLOW_PLANKS = registerBlock("overgrown_willow_planks", Block::new, Properties.ofFullCopy(Blocks.OAK_PLANKS));
      OVERGROWN_WILLOW_PLANKS_ITEM = registerBlockItem("overgrown_willow_planks", OVERGROWN_WILLOW_PLANKS);
      OVERGROWN_WILLOW_LOG = registerBlock("overgrown_willow_log", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.OAK_LOG));
      OVERGROWN_WILLOW_LOG_ITEM = registerBlockItem("overgrown_willow_log", OVERGROWN_WILLOW_LOG);
      OVERGROWN_WILLOW_WOOD = registerBlock("overgrown_willow_wood", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.OAK_WOOD));
      OVERGROWN_WILLOW_WOOD_ITEM = registerBlockItem("overgrown_willow_wood", OVERGROWN_WILLOW_WOOD);
      STRIPPED_OVERGROWN_WILLOW_LOG = registerBlock("stripped_overgrown_willow_log", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.STRIPPED_OAK_LOG));
      STRIPPED_OVERGROWN_WILLOW_LOG_ITEM = registerBlockItem("stripped_overgrown_willow_log", STRIPPED_OVERGROWN_WILLOW_LOG);
      STRIPPED_OVERGROWN_WILLOW_WOOD = registerBlock("stripped_overgrown_willow_wood", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.STRIPPED_OAK_WOOD));
      STRIPPED_OVERGROWN_WILLOW_WOOD_ITEM = registerBlockItem("stripped_overgrown_willow_wood", STRIPPED_OVERGROWN_WILLOW_WOOD);
      OVERGROWN_WILLOW_STAIRS = registerBlock("overgrown_willow_stairs", (properties) -> new StairBlock(OVERGROWN_WILLOW_PLANKS.defaultBlockState(), properties), Properties.ofFullCopy(Blocks.OAK_STAIRS));
      OVERGROWN_WILLOW_STAIRS_ITEM = registerBlockItem("overgrown_willow_stairs", OVERGROWN_WILLOW_STAIRS);
      OVERGROWN_WILLOW_SLAB = registerBlock("overgrown_willow_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.OAK_SLAB));
      OVERGROWN_WILLOW_SLAB_ITEM = registerBlockItem("overgrown_willow_slab", OVERGROWN_WILLOW_SLAB);
      OVERGROWN_WILLOW_FENCE = registerBlock("overgrown_willow_fence", FenceBlock::new, Properties.ofFullCopy(Blocks.OAK_FENCE));
      OVERGROWN_WILLOW_FENCE_ITEM = registerBlockItem("overgrown_willow_fence", OVERGROWN_WILLOW_FENCE);
      OVERGROWN_WILLOW_FENCE_GATE = registerBlock("overgrown_willow_fence_gate", (properties) -> new FenceGateBlock(WoodType.OAK, properties), Properties.ofFullCopy(Blocks.OAK_FENCE_GATE));
      OVERGROWN_WILLOW_FENCE_GATE_ITEM = registerBlockItem("overgrown_willow_fence_gate", OVERGROWN_WILLOW_FENCE_GATE);
      OVERGROWN_WILLOW_DOOR = registerBlock("overgrown_willow_door", (properties) -> new DoorBlock(BlockSetType.OAK, properties), Properties.ofFullCopy(Blocks.OAK_DOOR));
      OVERGROWN_WILLOW_DOOR_ITEM = registerBlockItem("overgrown_willow_door", OVERGROWN_WILLOW_DOOR);
      OVERGROWN_WILLOW_TRAPDOOR = registerBlock("overgrown_willow_trapdoor", (properties) -> new TrapDoorBlock(BlockSetType.OAK, properties), Properties.ofFullCopy(Blocks.OAK_TRAPDOOR));
      OVERGROWN_WILLOW_TRAPDOOR_ITEM = registerBlockItem("overgrown_willow_trapdoor", OVERGROWN_WILLOW_TRAPDOOR);
      OVERGROWN_WILLOW_PRESSURE_PLATE = registerBlock("overgrown_willow_pressure_plate", (properties) -> new PressurePlateBlock(BlockSetType.OAK, properties), Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE));
      OVERGROWN_WILLOW_PRESSURE_PLATE_ITEM = registerBlockItem("overgrown_willow_pressure_plate", OVERGROWN_WILLOW_PRESSURE_PLATE);
      OVERGROWN_WILLOW_BUTTON = registerBlock("overgrown_willow_button", (properties) -> new ButtonBlock(BlockSetType.OAK, 30, properties), Properties.ofFullCopy(Blocks.OAK_BUTTON));
      OVERGROWN_WILLOW_BUTTON_ITEM = registerBlockItem("overgrown_willow_button", OVERGROWN_WILLOW_BUTTON);
      OVERGROWN_WILLOW_SHELF = registerBlock("overgrown_willow_shelf", ShelfBlock::new, Properties.ofFullCopy(Blocks.OAK_SHELF));
      OVERGROWN_WILLOW_SHELF_ITEM = registerBlockItem("overgrown_willow_shelf", OVERGROWN_WILLOW_SHELF);
      OVERGROWN_WILLOW_SIGN = registerBlock("overgrown_willow_sign", (properties) -> new StandingSignBlock(WoodType.OAK, properties), Properties.ofFullCopy(Blocks.OAK_SIGN));
      OVERGROWN_WILLOW_WALL_SIGN = registerBlock("overgrown_willow_wall_sign", (properties) -> new WallSignBlock(WoodType.OAK, properties), dropsLike(Properties.ofFullCopy(Blocks.OAK_WALL_SIGN), "overgrown_willow_sign"));
      OVERGROWN_WILLOW_SIGN_ITEM = registerItem("overgrown_willow_sign", (properties) -> new StandingAndWallBlockItem(OVERGROWN_WILLOW_SIGN, OVERGROWN_WILLOW_WALL_SIGN, Direction.DOWN, properties));
      OVERGROWN_WILLOW_HANGING_SIGN = registerBlock("overgrown_willow_hanging_sign", (properties) -> new CeilingHangingSignBlock(WoodType.OAK, properties), Properties.ofFullCopy(Blocks.OAK_HANGING_SIGN));
      OVERGROWN_WILLOW_WALL_HANGING_SIGN = registerBlock("overgrown_willow_wall_hanging_sign", (properties) -> new WallHangingSignBlock(WoodType.OAK, properties), dropsLike(Properties.ofFullCopy(Blocks.OAK_WALL_HANGING_SIGN), "overgrown_willow_hanging_sign"));
      OVERGROWN_WILLOW_HANGING_SIGN_ITEM = registerItem("overgrown_willow_hanging_sign", (properties) -> new HangingSignItem(OVERGROWN_WILLOW_HANGING_SIGN, OVERGROWN_WILLOW_WALL_HANGING_SIGN, properties));
      OVERGROWN_WILLOW_FOLIAGE = registerBlock("overgrown_willow_foliage", (properties) -> new OvergrownWillowFoliageBlock(0.01F, properties), Properties.ofFullCopy(Blocks.OAK_LEAVES).destroyTime(0.7F).sound(SoundType.NETHER_WART));
      OVERGROWN_WILLOW_FOLIAGE_ITEM = registerBlockItem("overgrown_willow_foliage", OVERGROWN_WILLOW_FOLIAGE);
      OVERGROWN_WILLOW_SAPLING = registerBlock("overgrown_willow_sapling", OvergrownWillowSaplingBlock::new, Properties.ofFullCopy(Blocks.OAK_SAPLING).randomTicks().noCollision());
      OVERGROWN_WILLOW_SAPLING_ITEM = registerBlockItem("overgrown_willow_sapling", OVERGROWN_WILLOW_SAPLING);
      OVERGROWN_WILLOW_VINES = registerBlock("overgrown_willow_vines", OvergrownWillowVinesBlock::new, Properties.ofFullCopy(Blocks.VINE));
      OVERGROWN_WILLOW_VINES_ITEM = registerBlockItem("overgrown_willow_vines", OVERGROWN_WILLOW_VINES);
      OVERGROWN_WILLOW_VINES_PLANT = registerBlock("overgrown_willow_vines_plant", OvergrownWillowVinesPlantBlock::new, Properties.ofFullCopy(Blocks.VINE));
      SIFTSLATE_COAL_ORE = (DropExperienceBlock)registerBlock("siftslate_coal_ore", (properties) -> new DropExperienceBlock(UniformInt.of(0, 2), properties), Properties.ofFullCopy(Blocks.DEEPSLATE_COAL_ORE));
      SIFTSLATE_COAL_ORE_ITEM = registerBlockItem("siftslate_coal_ore", SIFTSLATE_COAL_ORE);
      SIFTSLATE_DIAMOND_ORE = (DropExperienceBlock)registerBlock("siftslate_diamond_ore", (properties) -> new DropExperienceBlock(UniformInt.of(3, 7), properties), Properties.ofFullCopy(Blocks.DEEPSLATE_DIAMOND_ORE));
      SIFTSLATE_DIAMOND_ORE_ITEM = registerBlockItem("siftslate_diamond_ore", SIFTSLATE_DIAMOND_ORE);
      SIFTSLATE_EMERALD_ORE = (DropExperienceBlock)registerBlock("siftslate_emerald_ore", (properties) -> new DropExperienceBlock(UniformInt.of(3, 7), properties), Properties.ofFullCopy(Blocks.DEEPSLATE_EMERALD_ORE));
      SIFTSLATE_EMERALD_ORE_ITEM = registerBlockItem("siftslate_emerald_ore", SIFTSLATE_EMERALD_ORE);
      SIFTSLATE_CHAROITE_ORE = (DropExperienceBlock)registerBlock("siftslate_charoite_ore", (properties) -> new DropExperienceBlock(UniformInt.of(2, 5), properties), Properties.ofFullCopy(Blocks.DEEPSLATE_LAPIS_ORE));
      SIFTSLATE_CHAROITE_ORE_ITEM = registerBlockItem("siftslate_charoite_ore", SIFTSLATE_CHAROITE_ORE);
      SIFTSLATE_SIFTITE_ORE = (DropExperienceBlock)registerBlock("siftslate_siftite_ore", (properties) -> new DropExperienceBlock(UniformInt.of(3, 7), properties), Properties.ofFullCopy(Blocks.DEEPSLATE_DIAMOND_ORE));
      SIFTSLATE_SIFTITE_ORE_ITEM = registerBlockItem("siftslate_siftite_ore", SIFTSLATE_SIFTITE_ORE);
      REINFORCED_SIFTSLATE_KEY = ResourceKey.create(BuiltInRegistries.BLOCK.key(), Identifier.fromNamespaceAndPath("the_sift", "reinforced_siftslate"));
      REINFORCED_SIFTSLATE = (Block)Registry.register(BuiltInRegistries.BLOCK, REINFORCED_SIFTSLATE_KEY, new Block(Properties.ofFullCopy(Blocks.REINFORCED_DEEPSLATE).strength(-1.0F, 3600000.0F).setId(REINFORCED_SIFTSLATE_KEY)));
      REINFORCED_SIFTSLATE_ITEM_KEY = ResourceKey.create(BuiltInRegistries.ITEM.key(), Identifier.fromNamespaceAndPath("the_sift", "reinforced_siftslate"));
      REINFORCED_SIFTSLATE_ITEM = (BlockItem)Registry.register(BuiltInRegistries.ITEM, REINFORCED_SIFTSLATE_ITEM_KEY, new BlockItem(REINFORCED_SIFTSLATE, (new Item.Properties()).setId(REINFORCED_SIFTSLATE_ITEM_KEY)));
   }
}
